pkg_name=report
pkg_version=0.2.0
pkg_origin=cheftv
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=("Apache-2.0")
pkg_description="Effortless Linux Audit Example"
pkg_scaffolding="chef/scaffolding-chef-inspec"
scaffold_automate_server_url='<AUTOMATE_URL>'
scaffold_automate_user='<USERNAME>'
scaffold_automate_token='<TOKEN>'
